export default function LoadEater(props) {
  return (
    <>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        style={{
          margin: "auto",
          background: "none",
          display: "block",
          shapeRendering: "auto",
        }}
        viewBox="0 0 100 100"
        width="100px"
        height="100px"
        {...props}
        preserveAspectRatio="xMidYMid"
      >
        <g>
          <circle cx={60} cy={50} r={4} fill="#f8b26a">
            <animate
              attributeName="cx"
              repeatCount="indefinite"
              dur="1.075268817204301s"
              values="95;35"
              keyTimes="0;1"
              begin="-0.6231000000000001s"
            />
            <animate
              attributeName="fill-opacity"
              repeatCount="indefinite"
              dur="1.075268817204301s"
              values="0;1;1"
              keyTimes="0;0.2;1"
              begin="-0.6231000000000001s"
            />
          </circle>
          <circle cx={60} cy={50} r={4} fill="#f8b26a">
            <animate
              attributeName="cx"
              repeatCount="indefinite"
              dur="1.075268817204301s"
              values="95;35"
              keyTimes="0;1"
              begin="-0.3069s"
            />
            <animate
              attributeName="fill-opacity"
              repeatCount="indefinite"
              dur="1.075268817204301s"
              values="0;1;1"
              keyTimes="0;0.2;1"
              begin="-0.3069s"
            />
          </circle>
          <circle cx={60} cy={50} r={4} fill="#f8b26a">
            <animate
              attributeName="cx"
              repeatCount="indefinite"
              dur="1.075268817204301s"
              values="95;35"
              keyTimes="0;1"
              begin="0s"
            />
            <animate
              attributeName="fill-opacity"
              repeatCount="indefinite"
              dur="1.075268817204301s"
              values="0;1;1"
              keyTimes="0;0.2;1"
              begin="0s"
            />
          </circle>
        </g>
        <g transform="translate(-15 0)">
          <path
            d="M50 50L20 50A30 30 0 0 0 80 50Z"
            fill="#5651e5"
            transform="rotate(90 50 50)"
          />
          <path d="M50 50L20 50A30 30 0 0 0 80 50Z" fill="#5651e5">
            <animateTransform
              attributeName="transform"
              type="rotate"
              repeatCount="indefinite"
              dur="1.075268817204301s"
              values="0 50 50;45 50 50;0 50 50"
              keyTimes="0;0.5;1"
            />
          </path>
          <path d="M50 50L20 50A30 30 0 0 1 80 50Z" fill="#5651e5">
            <animateTransform
              attributeName="transform"
              type="rotate"
              repeatCount="indefinite"
              dur="1.075268817204301s"
              values="0 50 50;-45 50 50;0 50 50"
              keyTimes="0;0.5;1"
            />
          </path>
        </g>
        {/* [ldio] generated by https://loading.io/ */}
      </svg>
    </>
  );
}
